name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Deploy to AWS EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          printf "%s" "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Ensure the target directory exists on EC2
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST "mkdir -p /home/ubuntu/app"

          # Copy files to EC2
          scp -o StrictHostKeyChecking=no -i private_key.pem -r client server package.json $AWS_USER@$AWS_HOST:/home/ubuntu/app/
          
          # Connect to EC2 and set up the application
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            cd /home/ubuntu/app
            npm install
            pm2 startOrRestart server/index.js --name server || pm2 restart server
          EOF
