name: MERN CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd server
          npm install

      - name: Check required files before SCP
        run: |
          ls -la
          test -f package.json && echo "package.json exists" || echo "package.json NOT found"
          test -f package-lock.json && echo "package-lock.json exists" || echo "package-lock.json NOT found"
          test -d server && echo "server directory exists" || echo "server directory NOT found"
          test -d client && echo "client directory exists" || echo "client directory NOT found"
          exit 1
        continue-on-error: true

      - name: Deploy to AWS EC2
        env:
          AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          echo "$AWS_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST "mkdir -p /home/ubuntu/app"
          scp -o StrictHostKeyChecking=no -i private_key.pem -r client server server/package.json server/package-lock.json $AWS_USER@$AWS_HOST:/home/ubuntu/app/
          ssh -o StrictHostKeyChecking=no -i private_key.pem $AWS_USER@$AWS_HOST << 'EOF'
            cd /home/ubuntu/app
            npm install
            pkill -f "node server.js" || true
            nohup node server.js > output.log 2>&1 &
          EOF